config/routes.rb
Rails.application.routes.draw do
  get 'statistics/listing'
  get 'statistics/weekly'
  get 'statistics/monthly'
  get 'statistics/yearly'

  get 'staff_members/show'
  get 'staff_members/listing'
  get 'staff_members/edit'
  get 'staff_members/index'
  get 'staff_members/destroy'
  get 'staffs/destroy'
  get 'staffs/show'

  get 'carts/checkout'
  post 'carts/checkout'
  get 'orders/show'
  
  get 'orders/destroy'

  get 'orders/create'
  get 'orders/ship'
  post 'orders/ship'
  devise_for :staffs
  
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'order_products/new_thing'

  get 'carts/show'
  get 'products/show', to: 'products#listing'
  get 'products/index'
  get 'products/edit'
  get 'products/listing'
  get 'products/destroy'
  get 'products/destroy'
  #post 'products/destroy'
  get 'products/new'
  post 'products/new'
  devise_for :users
  resources :staffs
  resources :staff_members
  resources :products#, only: [:new,:index, :edit, :listing]
  resources :carts, only: [:show, :checkout]
  resources :order_products, only: [:create,:new_thing,  :update, :destroy], defaults: {format: 'js'}
  resources :orders
  root 'products#index'
  #root 'home#index' ==> main home page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_products
  
  before_save :update_subtotal

  def subtotal
	order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
	def set_order_status
	  self.order_status_id = 1
	end

	def update_subtotal
	  self[:subtotal] = subtotal
	end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validate :in_stock
  before_save :finalize

  def unit_price
	if persisted?
	  self[:unit_price]
	else
	  (product.price - ((product.discount / 100.0) * product.price))
	end
   end

  def total_price
	unit_price * quantity
  end

private
  def in_stock
    if quantity > product.stock
	errors.add(:product, "not enough in stock.")
    end
  end
  def product_present
    if product.nil?
	errors.add(:product, "is not valid or is not in stock.")
    end
  end

  def order_present
    if order.nil?
	errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_products

	default_scope { where(active: true) }
  def self.search(search)
	where("name LIKE ?", "%#{search}%")
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
  def checkout
    @order_products = current_order.order_products
    s_total = 0
    name = "" 
    amount = 0
    product_desc = ""
    @order_products.each_with_index do |product_iter, index| 
        product = Product.find(product_iter.product_id)
	amount = product_iter.quantity
	if index == @order_products.size - 1 then
	    product_desc = product.name + " " + amount.to_s + ", " + product_desc
	else 
	    product_desc = product_desc + product.name + " " + amount.to_s 
	end
    end
    current_order.update_attributes(  :user_id => current_user.id, :tax => current_order.subtotal * 0.06, :total => current_order.subtotal * 1.06, :description => product_desc, :time => Time.now)
    @order_products.each do |buy_product|
	product = Product.find(buy_product.product_id)
	product.update_attribute(:stock, (product.stock - buy_product.quantity))
	s_total = s_total + (buy_product.quantity * buy_product.unit_price)
	buy_product.delete
    end
    
    session[:order_id] = nil #this forces a new order to be created
    
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/orders_controller.rb
 class OrdersController < ApplicationController
   def index
         @user = User.find(params[:user_id])
         @orders = current_user.orders
Add a comment to this line
   end
   def create
         @order.user = current_user
   end
 
   def ship
       @order = Order.find(params[:id]) 
       shipped = 2
       @order.update_attribute(:order_status_id, 2)
       redirect_to orders_show_path
   end

#   def show
#     @user_orders = Order.find(params[:id])
#   end
   
 end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def listing
  end

  def show
    @stats=Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/listing.html.erb
  <%= link_to "Past Week", statistics_weekly_path ,:method => :get%>
  <%= link_to "Past Month", statistics_monthly_path ,:method => :get%>
  <%= link_to "Past Year", statistics_yearly_path ,:method => :get%>
  <%= link_to "Total", statistics_listing_path ,:method => :get%>

<h2>Overall Statistics</h2>
  <% total = 0.0 %>
  <% @revenue = Order.all %>
  <% @revenue.each do |curr_rev| %>
    <% total = total + curr_rev.total.to_f %>
  <% end %>
<strong>Total Revenue:</strong>
<%= total %>


<h2>Complete Transaction History</h2>

<table style="width:100%">
  <thead>
    <tr>
      <th>Time</th>
      <th>Description</th>
      <th>Total</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats = Order.all  %>
    <% @stats.each do |curr_stat| %>
      <tr>
        <td><%= curr_stat.time %></td>
        <td><%= curr_stat.description %></td>
	<td><%= number_to_currency(curr_stat.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/statistics/monthly.html.erb
<%= link_to "Past Week", statistics_weekly_path ,:method => :get%>
  <%= link_to "Past Month", statistics_monthly_path ,:method => :get%>
  <%= link_to "Past Year", statistics_yearly_path ,:method => :get%>
  <%= link_to "Total", statistics_listing_path ,:method => :get%>

<h2>This Month's Statistics</h2>
  
  <% total = 0.0 %>
  <% @revenue = Order.where("created_at > ?", 1.months.ago) %>
  <% @revenue.each do |curr_rev| %>
    <% total = total + curr_rev.total.to_f %>
  <% end %>
<strong>This Months's Revenue:</strong>
<%= number_to_currency (total) %>


<h2>Transaction History for this Month</h2>

<table style="width:100%">
  <thead>
    <tr>
      <th>Time</th>
      <th>Description</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@stats = Order.where("created_at > ?", 1.months.ago) %>
    <% @stats.each do |curr_stat| %>
      <tr>
        <td><%= curr_stat.time %></td>
        <td><%= curr_stat.description %></td>
	<td><%= number_to_currency (curr_stat.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/statistics/weekly.html.erb
<%= link_to "Past Week", statistics_weekly_path ,:method => :get%>
  <%= link_to "Past Month", statistics_monthly_path ,:method => :get%>
  <%= link_to "Past Year", statistics_yearly_path ,:method => :get%>
  <%= link_to "Total", statistics_listing_path ,:method => :get%>

<h2>This Week's Statistics</h2>
  <% total = 0.0 %>
  <% @revenue = Order.where("created_at > ?", 7.days.ago) %>
  <% @revenue.each do |curr_rev| %>
    <% total = total + curr_rev.total.to_f %>
  <% end %>
<strong>This Week's Revenue:</strong>
<%= number_to_currency (total) %>


<h2>Transaction History for this Week</h2>

<table style="width:100%">
  <thead>
    <tr>
      <th>Time</th>
      <th>Description</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@stats = Order.where("created_at > ?", 7.days.ago) %>
    <% @stats.each do |curr_stat| %>
      <tr>
        <td><%= curr_stat.time %></td>
        <td><%= curr_stat.description %></td>
	<td><%= number_to_currency (curr_stat.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/statistics/yearly.html.erb
<%= link_to "Past Week", statistics_weekly_path ,:method => :get%>
  <%= link_to "Past Month", statistics_monthly_path ,:method => :get%>
  <%= link_to "Past Year", statistics_yearly_path ,:method => :get%>
  <%= link_to "Total", statistics_listing_path ,:method => :get%>

<h2>This Year's Statistics</h2>
  
  <% total = 0.0 %>
  <% @revenue = Order.where("created_at > ?", 1.years.ago) %>
  <% @revenue.each do |curr_rev| %>
    <% total = total + curr_rev.total.to_f %>
  <% end %>
<strong>This Year's Revenue:</strong>
<%= number_to_currency (total) %>


<h2>Transaction History for this Year</h2>

<table style="width:100%">
  <thead>
    <tr>
      <th>Time</th>
      <th>Description</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@stats = Order.where("created_at > ?", 1.years.ago) %>
    <% @stats.each do |curr_stat| %>
      <tr>
        <td><%= curr_stat.time %></td>
        <td><%= curr_stat.description %></td>
	<td><%= number_to_currency (curr_stat.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>