config/routes.rb
Rails.application.routes.draw do
  get 'statistics/listing'
  get 'statistics/weekly'
  get 'statistics/monthly'
  get 'statistics/yearly'

  get 'staff_members/show'
  get 'staff_members/listing'
  get 'staff_members/edit'
  get 'staff_members/index'
  get 'staff_members/destroy'
  get 'staffs/destroy'
  get 'staffs/show'

  get 'carts/checkout'
  post 'carts/checkout'
  get 'orders/show'
  
  get 'orders/destroy'

  get 'orders/create'
  get 'orders/ship'
  post 'orders/ship'
  devise_for :staffs
  
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'order_products/new_thing'

  get 'carts/show'
  get 'products/show', to: 'products#listing'
  get 'products/index'
  get 'products/edit'
  get 'products/listing'
  get 'products/destroy'
  get 'products/destroy'
  #post 'products/destroy'
  get 'products/new'
  post 'products/new'
  devise_for :users
  resources :staffs
  resources :staff_members
  resources :products#, only: [:new,:index, :edit, :listing]
  resources :carts, only: [:show, :checkout]
  resources :order_products, only: [:create,:new_thing,  :update, :destroy], defaults: {format: 'js'}
  resources :orders
  root 'products#index'
  #root 'home#index' ==> main home page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_products
  
  before_save :update_subtotal

  def subtotal
	order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
	def set_order_status
	  self.order_status_id = 1
	end

	def update_subtotal
	  self[:subtotal] = subtotal
	end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validate :in_stock
  before_save :finalize

  def unit_price
	if persisted?
	  self[:unit_price]
	else
	  (product.price - ((product.discount / 100.0) * product.price))
	end
   end

  def total_price
	unit_price * quantity
  end

private
  def in_stock
    if quantity > product.stock
	errors.add(:product, "not enough in stock.")
    end
  end
  def product_present
    if product.nil?
	errors.add(:product, "is not valid or is not in stock.")
    end
  end

  def order_present
    if order.nil?
	errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_products

	default_scope { where(active: true) }
  def self.search(search)
	where("name LIKE ?", "%#{search}%")
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
  def checkout
    @order_products = current_order.order_products
    s_total = 0
    name = "" 
    amount = 0
    product_desc = ""
    @order_products.each_with_index do |product_iter, index| 
        product = Product.find(product_iter.product_id)
	amount = product_iter.quantity
	if index == @order_products.size - 1 then
	    product_desc = product.name + " " + amount.to_s + ", " + product_desc
	else 
	    product_desc = product_desc + product.name + " " + amount.to_s 
	end
    end
    current_order.update_attributes(  :user_id => current_user.id, :tax => current_order.subtotal * 0.06, :total => current_order.subtotal * 1.06, :description => product_desc, :time => Time.now)
    @order_products.each do |buy_product|
	product = Product.find(buy_product.product_id)
	product.update_attribute(:stock, (product.stock - buy_product.quantity))
	s_total = s_total + (buy_product.quantity * buy_product.unit_price)
	buy_product.delete
    end
    
    session[:order_id] = nil #this forces a new order to be created
    
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/orders_controller.rb
 class OrdersController < ApplicationController
   def index
         @user = User.find(params[:user_id])
         @orders = current_user.orders
Add a comment to this line
   end
   def create
         @order.user = current_user
   end
 
   def ship
       @order = Order.find(params[:id]) 
       shipped = 2
       @order.update_attribute(:order_status_id, 2)
       redirect_to orders_show_path
   end

#   def show
#     @user_orders = Order.find(params[:id])
#   end
   
 end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
    @order_product = current_order.order_products.new
    if params[:search]
	@products = Product.search(params[:search]).order("name")
    else
	@products = Product.all.order('name')
    end
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end 
  def show
    @product=Product.find(params[:id])
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_listing_path
  end

  helper_method :productshowall
  def productshowall
	result = ActiveRecord::Base.connection.execute("SELECT * FROM products")
	return result
  end
  def edit
	@product = Product.find(params[:id])
  end
  def new
	@product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end 
  end
private
  def product_params
    params.require(:product).permit(:name, :price, :seller, :category, :stock, :discount)
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    @staff = Staff.all
  end
  def update
    @staff  = Staff.find(params[:id])
    if @staff.update(staff_params)
      redirect_to @staff
    else
      render 'edit'
    end
  end
  def show
    @staff  = Staff.find(params[:id])
  end

  def destroy
      @staff  = Staff.find(params[:id])
      @staff.destroy
      redirect_to managers_listing_path
  end

  def edit
        @staff  = Staff.find(params[:id])
  end
  def new
        @staff  = Staff.new
  end
  def create
    @staff  = Staff.new
    if @staff.save
      redirect_to @staff
    else
      render 'new'
    end
  end
private
  def staff_params
    params.require(:staff).permit(:name, :email, :manager)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/orders/_form.html.erb
<%= form_for (@order)  do |f| %> 
 <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_status_id %>
    <%= f.text_field :order_status_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Order#destroy</h1>
<p>Find me in app/views/order/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h2> Edit orders </h1>
<%= render 'form', order: @order%>

<%= link_to 'Back', orders_show_path %>

app/views/orders/listing.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Total</th>
      <th>Time</th>
      <th>Status</th>
      <th>Product</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <%if user_signed_in? %>
    	<% @orders = Order.find_by_user_id(2) %>
    <%if staff_signed_in? %>
        <% @orders = Order.find_by_user_id(2)  %>
    <%end%>
    <% @orders.each do |curr_order| %>
      <tr>
        <td><%= User.find(curr_order.user_id).name %></td>
        <td><%= curr_order.total %></td>
        <td><%= curr_order.created_at %></td>
        <td><%= OrderStatus.find( curr_order.order_status_id).name %></td>
        <% prod_id = (OrderProduct.find_by( curr_order.id)).product_id%>
	<td><%= Product.find(prod_id)%></td>
        <% @order = Order.find(curr_order.id)%>
        <td><%=  %></td>
        <td><%= %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/orders/show.html.erb
<h1>Customer Orders</h1>


<table style="width:100%">
  <thead>
    <tr>
      <th>User ID</th>
      <th>Time</th>
      <th>Description</th>
      <th>Total</th>
      <th>Order_Status</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <%if user_signed_in? %>
        <% @orders = Order.where(:user_id => current_user.id) %>
    <%elsif staff_signed_in? %>
        <% @orders = Order.all  %>
    <%end%>
    <% @orders.each do |curr_order| %>
      <tr>
        <td><%= curr_order.user_id %></td>
        <td><%= curr_order.time %></td>
        <td><%= curr_order.description %></td>
	<td><%= number_to_currency(curr_order.total) %></td>
	<td><%= if curr_order.order_status_id == 1 then
		    shipped = "Pending"
		elsif curr_order.order_status_id == 2 then
		    shipped = "Shipped" 
		end %></td>
	
	<% @order = Order.find(curr_order.id)%>
        <% if staff_signed_in? %>
        <td><%= link_to 'Ship', orders_ship_path(:id => @order.id), data:{confirm: 'Are you sure?'}%></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/staffs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/staffs/show.html.erb
<h1> Manager Updated <h1>
<%= link_to "Return to Staff", staff_members_listing_path %>
<%= link_to "Return to Homepage", root_path %>