config/routes.rb
Rails.application.routes.draw do
  get 'statistics/listing'
  get 'statistics/weekly'
  get 'statistics/monthly'
  get 'statistics/yearly'

  get 'staff_members/show'
  get 'staff_members/listing'
  get 'staff_members/edit'
  get 'staff_members/index'
  get 'staff_members/destroy'
  get 'staffs/destroy'
  get 'staffs/show'

  get 'carts/checkout'
  post 'carts/checkout'
  get 'orders/show'
  
  get 'orders/destroy'

  get 'orders/create'
  get 'orders/ship'
  post 'orders/ship'
  devise_for :staffs
  
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'order_products/new_thing'

  get 'carts/show'
  get 'products/show', to: 'products#listing'
  get 'products/index'
  get 'products/edit'
  get 'products/listing'
  get 'products/destroy'
  get 'products/destroy'
  #post 'products/destroy'
  get 'products/new'
  post 'products/new'
  devise_for :users
  resources :staffs
  resources :staff_members
  resources :products#, only: [:new,:index, :edit, :listing]
  resources :carts, only: [:show, :checkout]
  resources :order_products, only: [:create,:new_thing,  :update, :destroy], defaults: {format: 'js'}
  resources :orders
  root 'products#index'
  #root 'home#index' ==> main home page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_products
  
  before_save :update_subtotal

  def subtotal
	order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
	def set_order_status
	  self.order_status_id = 1
	end

	def update_subtotal
	  self[:subtotal] = subtotal
	end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validate :in_stock
  before_save :finalize

  def unit_price
	if persisted?
	  self[:unit_price]
	else
	  (product.price - ((product.discount / 100.0) * product.price))
	end
   end

  def total_price
	unit_price * quantity
  end

private
  def in_stock
    if quantity > product.stock
	errors.add(:product, "not enough in stock.")
    end
  end
  def product_present
    if product.nil?
	errors.add(:product, "is not valid or is not in stock.")
    end
  end

  def order_present
    if order.nil?
	errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_products

	default_scope { where(active: true) }
  def self.search(search)
	where("name LIKE ?", "%#{search}%")
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
  def checkout
    @order_products = current_order.order_products
    s_total = 0
    name = "" 
    amount = 0
    product_desc = ""
    @order_products.each_with_index do |product_iter, index| 
        product = Product.find(product_iter.product_id)
	amount = product_iter.quantity
	if index == @order_products.size - 1 then
	    product_desc = product.name + " " + amount.to_s + ", " + product_desc
	else 
	    product_desc = product_desc + product.name + " " + amount.to_s 
	end
    end
    current_order.update_attributes(  :user_id => current_user.id, :tax => current_order.subtotal * 0.06, :total => current_order.subtotal * 1.06, :description => product_desc, :time => Time.now)
    @order_products.each do |buy_product|
	product = Product.find(buy_product.product_id)
	product.update_attribute(:stock, (product.stock - buy_product.quantity))
	s_total = s_total + (buy_product.quantity * buy_product.unit_price)
	buy_product.delete
    end
    
    session[:order_id] = nil #this forces a new order to be created
    
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/orders_controller.rb
 class OrdersController < ApplicationController
   def index
         @user = User.find(params[:user_id])
         @orders = current_user.orders
Add a comment to this line
   end
   def create
         @order.user = current_user
   end
 
   def ship
       @order = Order.find(params[:id]) 
       shipped = 2
       @order.update_attribute(:order_status_id, 2)
       redirect_to orders_show_path
   end

#   def show
#     @user_orders = Order.find(params[:id])
#   end
   
 end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
    @order_product = current_order.order_products.new
    if params[:search]
	@products = Product.search(params[:search]).order("name")
    else
	@products = Product.all.order('name')
    end
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end 
  def show
    @product=Product.find(params[:id])
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_listing_path
  end

  helper_method :productshowall
  def productshowall
	result = ActiveRecord::Base.connection.execute("SELECT * FROM products")
	return result
  end
  def edit
	@product = Product.find(params[:id])
  end
  def new
	@product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end 
  end
private
  def product_params
    params.require(:product).permit(:name, :price, :seller, :category, :stock, :discount)
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    @staff = Staff.all
  end
  def update
    @staff  = Staff.find(params[:id])
    if @staff.update(staff_params)
      redirect_to @staff
    else
      render 'edit'
    end
  end
  def show
    @staff  = Staff.find(params[:id])
  end

  def destroy
      @staff  = Staff.find(params[:id])
      @staff.destroy
      redirect_to managers_listing_path
  end

  def edit
        @staff  = Staff.find(params[:id])
  end
  def new
        @staff  = Staff.new
  end
  def create
    @staff  = Staff.new
    if @staff.save
      redirect_to @staff
    else
      render 'new'
    end
  end
private
  def staff_params
    params.require(:staff).permit(:name, :email, :manager)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/products/_form.html.erb
<%= form_for (@product)  do |f| %> 
 <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price, class: :text_field, step: :any %>
  </div>

  <div class="field">
    <%= f.label :seller %>
    <%= f.text_field :seller %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :stock %>
    <%= f.number_field :stock %>
  </div>
  <%if current_staff.manager? %>
  <div class="field">
    <%= f.label :discount %>
    <%= f.number_field :discount %>
  </div>
  <div class="action">
    <%=f.submit%>
  </div>
  <%else%>
  <div class="field">
    <%= f.label :discount %>
   <%if @product.try(:discount).nil? %>
    <%= f.number_field :discount, :value => 0, :readonly => true%>
   <%else%>
    <%= f.number_field :discount, :value => @product.discount, :readonly => true%>
   <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%end%>
<% end %>

app/views/products/_product_row.html.erb
<div class="well">
 
  <div class="row">
    <div class="col-xs-8">
      <h4>Product Name: <%= product.name %></small></h4>
      <h4>Category: <%=  product.category %></small></h4>
      <%if product.category == 'Book'%> 
	<h4> Author: <%=product.seller%></small> </h4>
      <%else%>
	<h4> Developer: <%= product.seller%></small></h4>
      <%end%>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_product, remote: true do |f| %>
        <% if product.discount != 0 %>
	    <h4 class="text-right">Regular Price: <span style="color: red"><%= number_to_currency (product.price) %></span></h4>
	    <h4 class="text-right">Discount: <span style="color: blue"><%= number_to_percentage(product.discount, precision: 0) %></span></h4>
            <h4 class="text-right">Sale Price: <span style="color: green"><%= number_to_currency (product.price - ((product.discount / 100.0 )* product.price)) %></span></h4>
        <%else%>
	    <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency (product.price) %></span></h4>
	<%end%>
	<div class="input-group">
          <%= if !staff_signed_in? then f.number_field :quantity, value: 1, class: "form-control", min: 1 end %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= if user_signed_in? then f.submit "Add to Cart", class: "btn btn-primary" end%>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/edit.html.erb
<h2> Edit products </h1>
<%= render 'form', product: @product%>

<%= link_to 'Back', products_listing_path %>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>
 
<%= form_tag products_path, :method => "get" do %>
<p>
	<%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
	<%= submit_tag "Search", :name => nil %>
    
</p>
<% end %>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_product: @order_product %>
    <% end %>
  </div>
</div>

app/views/products/listing.html.erb
<h1>Products</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Seller</th>
      <th>Stock</th>
      <th>Discount</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @products = Product.all %>
    <% @products.each do |curr_product| %>
      <tr>
        <td><%= curr_product.name %></td>
        <td><%= curr_product.category %></td>
        <td><%= curr_product.price %></td>
	<td><%= curr_product.seller %></td>
	<td><%= curr_product.stock %></td>
	<td><%= curr_product.discount%></td>
	<% @product = Product.find(curr_product.id)%>
        <td><%= link_to 'Edit', edit_product_path(@product) %></td>
        <td><%= link_to 'Delete', product_path(curr_product), method: :delete, data:{confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form', product: Product.new %>
<%= link_to 'Back', products_listing_path %>

app/views/products/show.html.erb
<h1> Product Updated <h1>
<%= link_to "Return to Products", products_listing_path %>
<%= link_to "Return to Homepage", root_path %> 