config/routes.rb
Rails.application.routes.draw do
  get 'statistics/listing'
  get 'statistics/weekly'
  get 'statistics/monthly'
  get 'statistics/yearly'

  get 'staff_members/show'
  get 'staff_members/listing'
  get 'staff_members/edit'
  get 'staff_members/index'
  get 'staff_members/destroy'
  get 'staffs/destroy'
  get 'staffs/show'

  get 'carts/checkout'
  post 'carts/checkout'
  get 'orders/show'
  
  get 'orders/destroy'

  get 'orders/create'
  get 'orders/ship'
  post 'orders/ship'
  devise_for :staffs
  
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'order_products/new_thing'

  get 'carts/show'
  get 'products/show', to: 'products#listing'
  get 'products/index'
  get 'products/edit'
  get 'products/listing'
  get 'products/destroy'
  get 'products/destroy'
  #post 'products/destroy'
  get 'products/new'
  post 'products/new'
  devise_for :users
  resources :staffs
  resources :staff_members
  resources :products#, only: [:new,:index, :edit, :listing]
  resources :carts, only: [:show, :checkout]
  resources :order_products, only: [:create,:new_thing,  :update, :destroy], defaults: {format: 'js'}
  resources :orders
  root 'products#index'
  #root 'home#index' ==> main home page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_products
  
  before_save :update_subtotal

  def subtotal
	order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
	def set_order_status
	  self.order_status_id = 1
	end

	def update_subtotal
	  self[:subtotal] = subtotal
	end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validate :in_stock
  before_save :finalize

  def unit_price
	if persisted?
	  self[:unit_price]
	else
	  (product.price - ((product.discount / 100.0) * product.price))
	end
   end

  def total_price
	unit_price * quantity
  end

private
  def in_stock
    if quantity > product.stock
	errors.add(:product, "not enough in stock.")
    end
  end
  def product_present
    if product.nil?
	errors.add(:product, "is not valid or is not in stock.")
    end
  end

  def order_present
    if order.nil?
	errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_products

	default_scope { where(active: true) }
  def self.search(search)
	where("name LIKE ?", "%#{search}%")
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
  def checkout
    @order_products = current_order.order_products
    s_total = 0
    name = "" 
    amount = 0
    product_desc = ""
    @order_products.each_with_index do |product_iter, index| 
        product = Product.find(product_iter.product_id)
	amount = product_iter.quantity
	if index == @order_products.size - 1 then
	    product_desc = product.name + " " + amount.to_s + ", " + product_desc
	else 
	    product_desc = product_desc + product.name + " " + amount.to_s 
	end
    end
    current_order.update_attributes(  :user_id => current_user.id, :tax => current_order.subtotal * 0.06, :total => current_order.subtotal * 1.06, :description => product_desc, :time => Time.now)
    @order_products.each do |buy_product|
	product = Product.find(buy_product.product_id)
	product.update_attribute(:stock, (product.stock - buy_product.quantity))
	s_total = s_total + (buy_product.quantity * buy_product.unit_price)
	buy_product.delete
    end
    
    session[:order_id] = nil #this forces a new order to be created
    
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_products.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path(current_order.order_products), class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>H&S Storefront</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "H&S Storefront", root_path %></h1>
      </div>
      <div class="col-xs-6">
	<h3>Test Manager: username = "test@example.com" password = "wildcats"</h3>
        <%if !user_signed_in? && !staff_signed_in? %>
	  <%= link_to "Sign In", new_user_session_path, :method => :get %>
	  <%= link_to "Sign Up", new_user_registration_path, :method => :get %>
	  <%= link_to "Staff Registration", new_staff_registration_path, :method => :get %>
	<%elsif !staff_signed_in? && user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
	<%end%>
	<%if !staff_signed_in? && !user_signed_in? %>
          <%= link_to "Staff Sign In", new_staff_session_path, :method => :get %>
        <%elsif staff_signed_in? && !user_signed_in?%>
          <%= link_to "Sign Out", destroy_staff_session_path, :method => :delete %>
	<%end %>
      <%if user_signed_in? || staff_signed_in?%>
      	<%= link_to "Orders", orders_show_path ,:method => :get%>
      <%end%> 
      <%if staff_signed_in? %>
      <%= link_to "Inventory", products_listing_path, :method => :get %>
      <% if current_staff.manager? %>
        <%= link_to "Staff", staff_members_listing_path, :method => :get %>
      <% end %>
      <% if current_staff.manager? %>
        <%= link_to "Transaction History", statistics_listing_path, :method => :get %>
      <% end %>
    <%end %>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= if !staff_signed_in? then render 'layouts/cart_text' end %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>
  <div> 
  <div class="col-xs-6">
  </div>
</body>
</html>